--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: []

comment: 
constants: []

full_name: ActionController::Caching::ConfigMethods
includes: []

instance_methods: 
- !ruby/object:RI::MethodSummary 
  name: cache_store
- !ruby/object:RI::MethodSummary 
  name: cache_store=
name: ConfigMethods
superclass: 
