--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: ActiveSupport::Configurable::ClassMethods#config
is_singleton: false
name: config
params: ()
visibility: public
