--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: ActiveSupport::Configurable::ClassMethods#config_accessor
is_singleton: false
name: config_accessor
params: (*names)
visibility: public
