--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: Return an array containing the values associated with the given keys.
full_name: Multimap#values_at
is_singleton: false
name: values_at
params: (*keys)
visibility: public
