--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: []

comment: 
- !ruby/struct:SM::Flow::H 
  level: 1
  text: Active Model Mass-Assignment Security
constants: []

full_name: ActiveModel::MassAssignmentSecurity
includes: []

instance_methods: 
- !ruby/object:RI::MethodSummary 
  name: mass_assignment_authorizer
- !ruby/object:RI::MethodSummary 
  name: sanitize_for_mass_assignment
name: MassAssignmentSecurity
superclass: 
